# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73601e0161d9260f8309807522c0eaa9ab91457090f1e5b905326bc007262fa4b8fbb9c3aea9f6264d345238568b498138e7be55531eed1af011d64651ace129

test:
  secret_key_base: adbe8bbbc7c1bfccff7d02e227ec3a4564502118820345afe1ea1b2d7bacc1a66d9f970a71f94b9259a53fceb5fbf40efa99b1db49c0744a20f072ee8f0aaea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
